# Generated by Django 3.0.5 on 2020-04-26 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200426_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='cat_name',
        ),
    ]
