# Generated by Django 3.0.5 on 2020-04-26 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200426_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='attribute_type',
        ),
    ]
