# Generated by Django 3.0.5 on 2020-04-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_attribute_attribute_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_attributes',
            new_name='product_variants',
        ),
    ]
