# Generated by Django 3.0.5 on 2020-04-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20200426_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product_image/default_product_image.png', null=True, upload_to='product_image/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_variants',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_attribute', to='product.Attribute'),
        ),
    ]
