"""
Django settings for OnlineShopping project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from decouple import config

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['127.0.0.1', 'localhost','192.168.43.142','59bccb36.ngrok.io']

# Add site url without add '/' slash at the end
SITE_URL = config('SITE_URL')
APPLICATION_NAME = config('APPLICATION_NAME')
# Application definition

INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',

	'store',
	'product',

	'rest_framework',
	'sorl.thumbnail',
	# 'pwa',
	'accounts',
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'OnlineShopping.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': ['template'],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',

				'store.context_processors.site_info',
			],
		},
	},
]

WSGI_APPLICATION = 'OnlineShopping.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
	'default': {
	    'ENGINE': 'django.db.backends.sqlite3',
	    'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
	}
	# 'default':{
	# 	'ENGINE': 'django.db.backends.postgresql',
	# 	'NAME':	config('DB_NAME'),
	# 	'USER' : config('DB_USER'),
	# 	'PASSWORD' : config('DB_PASSWORD'),
	# 	'HOST' : config('DB_HOST'),
	# 	'PORT' : config('DB_PORT'),
	# }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'static/staticfiles')
STATIC_URL = '/static/'
STATICFILES_DIRS = [
	os.path.join(BASE_DIR, 'static/')
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR+'/media/'
FULL_MEDIA_URL = SITE_URL+MEDIA_URL


#---------GOOGLE RECHAPCHA-------------
# V3
GOOGLE_RECAPTCHA_SITE_KEY_V3 = config('GOOGLE_RECAPTCHA_SITE_KEY_V3')
GOOGLE_RECAPTCHA_SECRET_KEY_V3 = config('GOOGLE_RECAPTCHA_SECRET_KEY_V3')

# V2
GOOGLE_RECAPTCHA_SITE_KEY_V2 = config('GOOGLE_RECAPTCHA_SITE_KEY_V2')
GOOGLE_RECAPTCHA_SECRET_KEY_V2 = config('GOOGLE_RECAPTCHA_SECRET_KEY_V2')



# Thumbnail setting 
THUMBNAIL_DEBUG = DEBUG
THUMBNAIL_PREFIX  = 'cache/'
THUMBNAIL_BACKEND = 'store.set_thumbnail_name.SEOThumbnailBackend'
# THUMBNAIL_BACKEND = 'sorl.thumbnail.base.ThumbnailBackend'
# THUMBNAIL_KVSTORE = 'sorl.thumbnail.kvstores.cached_db_kvstore.KVStore'
# THUMBNAIL_ENGINE = 'sorl.thumbnail.engines.pil_engine.Engine'




#  REST FRAMEWORK SETTING START 

DEFAULT_RENDERER_CLASSES = (
	'rest_framework.renderers.JSONRenderer',
)

if DEBUG:
	DEFAULT_RENDERER_CLASSES = DEFAULT_RENDERER_CLASSES + (
		'rest_framework.renderers.BrowsableAPIRenderer',
	)


REST_FRAMEWORK = {
	'DEFAULT_AUTHENTICATION_CLASSES': [
		'rest_framework.authentication.BasicAuthentication',
		'rest_framework.authentication.SessionAuthentication',
		'rest_framework.authentication.TokenAuthentication',
		
	],
	'DEFAULT_PERMISSION_CLASSES': (
		# 'rest_framework.permissions.IsAdminUser',
		# 'rest_framework.permissions.IsAuthenticated',
	),
	'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
	'PAGE_SIZE': 4,

	# Disable browsable api
	'DEFAULT_RENDERER_CLASSES': DEFAULT_RENDERER_CLASSES

}


#  REST FRAMEWORK SETTING END 


EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' 
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'testsite_app'
EMAIL_HOST_PASSWORD = 'mys3cr3tp4ssw0rd'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'TestSite Team <noreply@example.com>'